services:

  postgres:
    image: postgres:16
    container_name: tienda-postgres
    environment:
      POSTGRES_DB: tiendadb
      POSTGRES_USER: tienda
      POSTGRES_PASSWORD: tienda123
    ports:
      - "5440:5432"
    volumes:
      - tienda-datos:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tienda -d tiendadb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tienda-app-container
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/tiendadb
      DB_USER: tienda
      DB_PASSWORD: tienda123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  tienda-datos: